/* FINAL SHOWDOWN - an original floating sky arena mode. Gameplay-only module. */
(() => {
  'use strict';
  const T=window.THREE,V=window.PartyVisuals,$=id=>document.getElementById(id);
  const A={
    names:['You','Mochi','Sprinkle','Bubbles','Pip','Jelly','Noodle','Taffy','Peach','Waffle','Fizz','Pudding'],
    colors:[0xff668f,0x55c8ed,0xffc85a,0x9b87f5,0x61d69f,0xff965c,0xf07ad1,0x68a8ff,0xc2dc5c,0xef7e62,0x50d4c3,0xc18aff],
    skills:[{name:'Energy Bomb',icon:'✦',kind:'bomb'},{name:'Lightning Zone',icon:'ϟ',kind:'lightning'},{name:'Ice Blast',icon:'❄',kind:'ice'},{name:'Shield',icon:'◈',kind:'shield'},{name:'Giant Mode',icon:'★',kind:'giant'}]
  };
  let scene,world,effect,root,player,actors=[],arena=[],items=[],projectiles=[],state='idle',elapsed=0,clock=0,ability=null,targetRing,core,warning,light,oldHud,spectatorIndex=0;
  const center=new T.Vector3(0,0,0), ARENA_TIME=300;
  function mat(c,kind='plastic'){return V.material(c,kind)}
  function mesh(g,geo,m,x=0,y=0,z=0){const o=new T.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;g.add(o);return o}
  function box(g,w,h,d,c,x,y,z,r=.18){return mesh(g,V.boxGeo?V.boxGeo(w,h,d,r):new T.BoxGeometry(w,h,d),mat(c),x,y,z)}
  function spawnArena(root){
    const g=new T.Group();g.position.y=-.05;root.add(g);arena=[];
    const centerPad=V.platform(0,13,0x3cafa9,22);centerPad.position.z=-11;centerPad.position.y=.05;g.add(centerPad);arena.push({g:centerPad,anchorX:0,anchorZ:0,r:6.4,active:true,outer:false});
    const spots=[[0,-14],[14,0],[0,14],[-14,0],[10,-10],[-10,-10],[10,10],[-10,10]];
    spots.forEach((p,i)=>{const plet=V.platform(0,6.5,[0xff8095,0x62c7d2,0xffc85e,0x9b87f5][i%4],8);plet.position.set(p[0],i%3?-.8:.15,p[1]-4);plet.rotation.y=(i%2)*.18;g.add(plet);arena.push({g:plet,anchorX:p[0],anchorZ:p[1],r:3.15,active:true,outer:true,delay:86+i*13,baseY:plet.position.y,falling:0});});
    const rim=new T.Group();g.add(rim);for(let i=0;i<12;i++){const a=i*Math.PI/6,x=Math.cos(a)*18,z=Math.sin(a)*18;V.cylinder(rim,.28,.18,2.4,i%2?0xffc85e:0xf36981,x,0,z,'metal',12);}
    core=V.orb(g,1.35,1.35,1.35,0xffd35d,0,2.1,0,'glow');core.userData.baseScale=1;
    for(let i=0;i<4;i++){const r=V.torus(g,2.1+i*.35,.07,[0xfff1ce,0xff7e9e,0x70d6e2,0xffc85e][i],0,2.1,0,'glow');r.rotation.x=Math.PI/2;r.userData.orbit=i*.8;}
    const crystalRoot=new T.Group();g.add(crystalRoot);for(let i=0;i<12;i++){const a=i*Math.PI/6;V.orb(crystalRoot,.24,.8,.24,i%2?0x70d6e2:0xf36981,Math.cos(a)*10,.7+Math.sin(i)*.25,Math.sin(a)*10,'glow');}
    return g;
  }
  function build(root){
    world=new T.Group();root.add(world);effect=new T.Group();root.add(effect);spawnArena(world);
    const clouds=new T.Group();root.add(clouds);for(let i=0;i<8;i++){const cg=new T.Group();cg.position.set((i%2?1:-1)*(24+i*4),-3+(i%3)*2, -12+i*10);V.orb(cg,4,1.2,2,0xe5eff1,0,0,0,'rubber',true);V.orb(cg,2.7,1.6,1.6,0xf7ffff,2,0,0,'rubber',true);cg.userData.phase=i;clouds.add(cg);}
  }
  function nameTag(name,isPlayer){
    const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const ctx=canvas.getContext('2d');ctx.fillStyle=isPlayer?'#f36981':'#263e60';ctx.fillRect(4,4,248,56);ctx.fillStyle='#fff5df';ctx.font='900 28px Segoe UI';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(isPlayer?'YOU':name,128,33);
    const sprite=new T.Sprite(new T.SpriteMaterial({map:new T.CanvasTexture(canvas),transparent:true,depthTest:false}));sprite.position.y=2.25;sprite.scale.set(1.75,.44,1);return sprite;
  }
  function actor(name,color,idx){const group=V.character(color);group.add(nameTag(name,idx===0));group.position.set(0,1.15,0);world.add(group);const theta=idx/11*Math.PI*2;const radius=idx?4.1:0;const skill=A.skills[Math.floor(Math.random()*A.skills.length)];return{name,color,group,x:Math.cos(theta)*radius,z:Math.sin(theta)*radius,y:0,vy:0,hp:100,shield:0,stun:0,slow:0,giant:0,eliminated:false,finished:false,heading:theta+Math.PI,skill,abilityCooldown:0,ai:idx>0,type:idx%3===0?'aggressive':idx%3===1?'defensive':'balanced',target:0,think:0,hitFlash:0};}
  function clear(){if(!world)return;world.traverse(o=>{if(o.geometry&&!o.isInstancedMesh)o.geometry.dispose?.();if(o.material){const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose?.());}});scene.remove(world);scene.remove(effect);actors=[];arena=[];items=[];projectiles=[];world=null;effect=null;}
  function init(s){scene=s;root=new T.Group();root.name='FinalShowdownArena';root.visible=false;scene.add(root);build(root);return root;}
  function placeActors(){actors=[];for(let i=0;i<12;i++){const a=actor(A.names[i],A.colors[i],i);const theta=i/12*Math.PI*2;const radius=i===0?4.2:(i<5?5.4:(i<9?10.2:14.2));a.x=Math.cos(theta)*radius;a.z=Math.sin(theta)*radius;a.group.position.set(a.x,1.15,a.z);a.group.visible=true;actors.push(a);}player=actors[0];}
  function spawnItems(){items=[];const kinds=['Health Orb','Speed Boost','Shield','Energy Bomb','Jump Boost','Magnet'];for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=7+(i%3)*2,g=new T.Group();g.position.set(Math.cos(a)*r,.7,Math.sin(a)*r);const color=[0xf36981,0x68d9a5,0x75c8ff,0xffc85e][i%4];V.orb(g,.32,.32,.32,color);V.torus(g,.48,.06,0xfff1ce);world.add(g);items.push({g,x:g.position.x,z:g.position.z,type:kinds[i%kinds.length],respawn:0,active:true});}}
  function begin(){if(state!=='idle')return;actors.forEach(a=>{if(a.group.parent)a.group.parent.remove(a.group);});items.forEach(i=>{if(i.g.parent)i.g.parent.remove(i.g);});actors=[];items=[];root.visible=true;world.visible=true;placeActors();spawnItems();state='countdown';elapsed=0;ability=null;spectatorIndex=0;items.forEach(i=>i.respawn=0);$('showdownHud').classList.remove('hidden');$('showdownWarning').classList.add('hidden');$('countdown').classList.remove('hidden');$('countdown').textContent='3';let n=3;const timer=setInterval(()=>{n--;if(n>0){$('countdown').textContent=String(n);}else if(n===0){$('countdown').textContent='SHOWDOWN!';state='active';}else{$('countdown').classList.add('hidden');clearInterval(timer);}},900);setModeUI(true);}
  function setModeUI(on){$('aliveLabel').textContent=on?'ALIVE':'PLAYERS LEFT';$('cpLabel').textContent=on?'ARENA':'CHECKPOINT';$('cpText').textContent=on?'SAFE':'0/4';$('progressWrap')?.classList.toggle('hidden',on);$('showdownHud').classList.toggle('hidden',!on);if(on)updateAbilityUI();}
  function alive(){return actors.filter(a=>!a.eliminated)}
  function nearest(a){let best=null,d=Infinity;actors.forEach(o=>{if(o===a||o.eliminated)return;const dd=Math.hypot(a.x-o.x,a.z-o.z);if(dd<d){d=dd;best=o;}});return best;}
  function inside(a){const shrink=Math.max(3.2,18*(1-elapsed/ARENA_TIME));return Math.hypot(a.x,a.z)<shrink;}
  function supported(a){return arena.some(p=>p.active&&Math.hypot(a.x-p.anchorX,a.z-p.anchorZ)<=p.r);}
  function damage(a,n,source){if(a.eliminated||a.shield>0)return false;a.hp=Math.max(0,a.hp-n);a.stun=Math.max(a.stun,.22);a.hitFlash=.25;if(source){const dx=a.x-source.x,dz=a.z-source.z,l=Math.hypot(dx,dz)||1;a.x+=dx/l*(1.2+source.power*.12);a.z+=dz/l*(1.2+source.power*.12);a.vy=Math.max(a.vy,source.power*.45);}if(a.hp<=0){eliminate(a);return true;}return false;}
  function eliminate(a){if(a.eliminated)return;a.eliminated=true;a.group.visible=false;V.emit('hit',a.group.position,a.color,16);if(a===player){$('toast').textContent='ELIMINATED · SPECTATOR MODE';$('toast').classList.remove('hidden');}}
  function cast(a){if(a.abilityCooldown>0||a.eliminated)return;const kind=a.skill.kind;const target=a===player?{x:a.x+Math.sin(a.heading)*5,z:a.z+Math.cos(a.heading)*5}:nearest(a)||a; a.abilityCooldown=8;if(a===player){const targetUI=$('showdownTarget');if(targetUI)targetUI.textContent='TARGET: '+Math.round(target.x)+', '+Math.round(target.z);}
    if(kind==='shield'){a.shield=3;return;}if(kind==='giant'){a.giant=5;return;}
    projectiles.push({owner:a,kind,x:target.x,z:target.z,t:kind==='bomb'?1.0:.45,range:kind==='bomb'?3.2:2.4,power:kind==='ice'?25:kind==='lightning'?34:42});
  }
  function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.t-=dt;if(p.t>0)continue;actors.forEach(a=>{if(a===p.owner||a.eliminated)return;const d=Math.hypot(a.x-p.x,a.z-p.z);if(d<p.range)damage(a,p.power,{x:p.x,z:p.z,power:p.power});});projectiles.splice(i,1);V.emit('hit',new T.Vector3(p.x,1,p.z),p.kind==='ice'?0x8de9ff:0xffd35d,14);}}
  function updateItems(dt){items.forEach(it=>{if(!it.active){it.respawn-=dt;if(it.respawn<=0){it.active=true;it.g.visible=true;}return;}it.g.rotation.y+=dt*2;actors.forEach(a=>{if(a.eliminated||Math.hypot(a.x-it.x,a.z-it.z)>.9)return;it.active=false;it.respawn=11+Math.random()*4;it.g.visible=false;if(it.type==='Health Orb')a.hp=Math.min(100,a.hp+30);if(it.type==='Shield')a.shield=3;if(it.type==='Speed Boost')a.slow=0;a.abilityCooldown=Math.max(0,a.abilityCooldown-2);});});}
  function updateActor(a,dt){if(a.eliminated)return;a.stun=Math.max(0,a.stun-dt);a.shield=Math.max(0,a.shield-dt);a.slow=Math.max(0,a.slow-dt);a.giant=Math.max(0,a.giant-dt);a.abilityCooldown=Math.max(0,a.abilityCooldown-dt);a.vy-=24*dt;a.y+=a.vy*dt;if(a.y<0){a.y=0;a.vy=0;}const safe=inside(a),speed=(a===player?7.4:5.1)*(a.slow?0.65:1)*(a.giant?.78:1);if(!supported(a)){a.y-=8*dt;if(a.y<-.8)eliminate(a);}if(!safe){damage(a,16,{x:0,z:0,power:1.2});a.x*=Math.max(0,1-dt*.8);a.z*=Math.max(0,1-dt*.8);}
    if(a.stun<=0){let dx=0,dz=0;if(a===player){const w=window.__showdownKeys||{},yaw=window.__showdownYaw||0,h=(w.KeyD?1:0)-(w.KeyA?1:0),v=(w.KeyW?1:0)-(w.KeyS?1:0);dx=-Math.sin(yaw)*v-Math.cos(yaw)*h;dz=Math.cos(yaw)*v-Math.sin(yaw)*h;}else{const t=nearest(a);if(t&&a.type==='aggressive'){dx=t.x-a.x;dz=t.z-a.z;}else{const ang=Math.atan2(-a.z,-a.x)+Math.sin(clock*.7+a.x)*.35;dx=Math.cos(ang);dz=Math.sin(ang);}}const l=Math.hypot(dx,dz);if(l>.01){a.x+=dx/l*speed*dt;a.z+=dz/l*speed*dt;a.heading=Math.atan2(dx,dz);}}
    actors.forEach(o=>{if(o===a||o.eliminated)return;const dx=a.x-o.x,dz=a.z-o.z,d=Math.hypot(dx,dz);if(d>0&&d<1.35){const push=(1.35-d)*.5;a.x+=dx/d*push;a.z+=dz/d*push;if(a.type==='aggressive'&&a.stun<=0)damage(o,9,{x:a.x,z:a.z,power:a.giant?8:4});}});
    if(a===player&&window.__showdownKeys?.Space&&a.y<=.02)a.vy=10;if(a.ai){a.think-=dt;if(a.think<=0){a.think=.25+Math.random()*.55;if(Math.random()<.08)cast(a);}}a.group.position.set(a.x,1.15+a.y,a.z);a.group.scale.setScalar(a.giant?1.34:1);const visual=a.group.userData.visual;if(visual){if(a.shield>0){if(!visual.shield){visual.shield=V.orb(a.group,1.15,1.3,1.15,0x75c8ff,0,0,0,'jelly');}visual.shield.visible=true;}else if(visual.shield)visual.shield.visible=false;}V.animateCharacter({group:a.group,x:a.x,y:a.y,z:a.z,vy:a.vy,stun:a.stun,finished:false,eliminated:false,color:a.color},dt,'race');}
  function updateCollapse(){arena.forEach(p=>{if(!p.outer||p.falling||elapsed<p.delay)return;p.falling=1;});arena.forEach(p=>{if(!p.falling)return;p.falling+=.02;const t=p.falling-1;p.g.rotation.z=Math.sin(t*18)*.04;p.g.position.y=p.baseY-t*t*1.8;if(t>1.2){p.active=false;p.g.visible=false;}});}
  function update(dt){if(state!=='active')return;elapsed+=dt;clock+=dt;updateCollapse();updateProjectiles(dt);updateItems(dt);actors.forEach(a=>updateActor(a,dt));if(player&&player.abilityCooldown<=0&&window.__showdownKeys?.KeyE)cast(player);const living=alive();if(elapsed>=ARENA_TIME&&living.length>1){const winner=living.slice().sort((a,b)=>Math.hypot(a.x,a.z)-Math.hypot(b.x,b.z))[0];living.forEach(a=>{if(a!==winner)eliminate(a);});}if(living.length<=3){$('showdownPhase').textContent=living.length===2?'FINAL DUEL':'FINAL 3';}else $('showdownPhase').textContent='SURVIVE';if(living.length<=1){state='result';$('toast').textContent='CHAMPION!';$('toast').classList.remove('hidden');}updateUI();}
  function updateUI(){const living=alive();$('playersLeft').textContent=String(living.length)+'/12';const left=Math.max(0,ARENA_TIME-elapsed);$('showdownTimer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(Math.floor(left%60)).padStart(2,'0');const danger=player&&!inside(player);$('showdownWarning').classList.toggle('hidden',!danger);$('showdownPhase').textContent=living.length<=2?'FINAL DUEL':living.length<=3?'FINAL 3':elapsed>210?'COLLAPSE':'SURVIVE';if(core){core.scale.setScalar(1+elapsed/ARENA_TIME*1.8);core.material.emissiveIntensity=.4+elapsed/ARENA_TIME*1.4;}if(player)$('abilityStatus').textContent=player.abilityCooldown>0?player.abilityCooldown.toFixed(1):'READY';}
  function updateAbilityUI(){if(!player)return;$('abilityName').textContent=player.skill.name.toUpperCase();$('abilityIcon').textContent=player.skill.icon;$('abilityStatus').textContent=player.abilityCooldown>0?player.abilityCooldown.toFixed(1):'READY';}
  function cycleSpectator(step){const living=alive();if(!living.length)return;spectatorIndex=(spectatorIndex+step+living.length)%living.length;}
  function end(){actors.forEach(a=>a.group.visible=false);items.forEach(i=>i.g.visible=false);state='idle';if(root)root.visible=false;$('showdownHud').classList.add('hidden');setModeUI(false);}
  window.FinalShowdown={init,begin,update,end,cycleSpectator,get active(){return state!=='idle'},get state(){return state},get actors(){return actors},get player(){return player},get focus(){const living=alive();return player?.eliminated?(living[spectatorIndex%Math.max(1,living.length)]||player):player},get arena(){return arena},get root(){return root}};
})();
